### ISSUE TITLE
Create Header

### ISSUE THREAD

**Issue by jromest** [fccManila/fccmanila.github.io#1]
Here's what you will be building:
![Header](https://user-images.githubusercontent.com/25174423/66144256-13bb1f00-e63b-11e9-9312-d0814d49b8b6.png)

Please refer to the [design](https://www.figma.com/proto/ZDkwUTcrWZvv67wCdnt6Xu/freeCodeCamp-Manila?node-id=47%3A1&scaling=scale-down-width), and make sure you read the [project plan](https://github.com/fccManila/fccmanila.github.io/blob/develop/PROJECT_PLAN.md).

If you have any questions, don't hesitate to ask 😄

**Comment by gxmp** [comment]
Hi! Can I work on this?

**Comment by jromest** [comment]
The header has been merged through #16, closing this now.
