### ISSUE TITLE
Create Hero

### ISSUE THREAD

**Issue by jromest** [fccManila/fccmanila.github.io#2]
Here's what you will be building:
![Hero](https://user-images.githubusercontent.com/25174423/66144853-31d54f00-e63c-11e9-8898-63bc1876bda3.png)

Please refer to the [design](https://www.figma.com/proto/ZDkwUTcrWZvv67wCdnt6Xu/freeCodeCamp-Manila?node-id=47%3A1&scaling=scale-down-width), and make sure you read the [project plan](https://github.com/fccManila/fccmanila.github.io/blob/develop/PROJECT_PLAN.md).

If you have any questions, don't hesitate to ask 😄

**Comment by engrleir** [comment]
I want to contribute. Please assign me to this. Thanks!

**Comment by jromest** [comment]
Hey @engrleir, thank you for expressing your interest in contributing to this project, feel free to work on this issue.

**Comment by jromest** [comment]
Hi @rcode321, are you still working on this issue?

**Comment by rodprogramdev** [comment]
Hi sir is this issue still open? Can I try to help and contribute? Thanks

**Comment by rcode321** [comment]
yes bro, sorry diko na nafollow up medyo busy kasi

**Comment by rodprogramdev** [comment]
Still working on how I can make the wave css effect, looking for ways on how to use either SVG and Clip-path for the design
![1](https://user-images.githubusercontent.com/44669373/68449690-253bac00-0223-11ea-91a2-a96c0c57fe94.png)

**Comment by jromest** [comment]
Hey @rodprogramdev, thank you for expressing your interest in contributing to this project, feel free to work on this issue. Looking good on the hero section, I think using SVG is much easier to use especially for responsive design.

**Comment by rodprogramdev** [comment]
Thanks sir, currently working on it as of now.
![3](https://user-images.githubusercontent.com/44669373/68557943-6675cb00-0472-11ea-8bef-db55de8e9565.png)

**Comment by rodprogramdev** [comment]
![1](https://user-images.githubusercontent.com/44669373/68557974-89a07a80-0472-11ea-9ff7-cd6cdc7d96da.png)

**Comment by rodprogramdev** [comment]
Hi sir I'm still working on the wave svg file and tried GIMP for making SVG, there was actually no supported format. Went to using INKSCAPE for the wave design. Still working on the size and still experimenting with how to use svg. Need to work on responsiveness when I get to learn how to apply the proper position.
![5](https://user-images.githubusercontent.com/44669373/68759543-dccd2580-064a-11ea-8a63-1d932d225213.png)
![8](https://user-images.githubusercontent.com/44669373/68759554-dfc81600-064a-11ea-8d7c-4e7f88db8519.png)


![3](https://user-images.githubusercontent.com/44669373/68759524-d343bd80-064a-11ea-9b3c-1a737cfe418a.png)

**Comment by rodprogramdev** [comment]
Hi sir, this is actually my first time to contribute and still working on understanding the workflow. I've tried installing the NODEjs and Yarn into my machine and did some reading. Also made the repository for you to be able to view the progress. I'm not yet that familiar with building branches so I'll be working on it in my repository first. Thank you
![3](https://user-images.githubusercontent.com/44669373/69110710-7ca90a00-0ab6-11ea-9467-712a0cbd193c.png)
![6](https://user-images.githubusercontent.com/44669373/69110726-8468ae80-0ab6-11ea-901b-839055a8721d.png)
![9](https://user-images.githubusercontent.com/44669373/69110908-f3de9e00-0ab6-11ea-825f-c4b49a81c480.png)

**Comment by rodprogramdev** [comment]
https://rodprogramdev.github.io/fccManilaCreateHero/

**Comment by rodprogramdev** [comment]
No responsiveness yet, still working on the wave effect sir thanks

**Comment by rodprogramdev** [comment]
Hi sir here is the updated version still working on the break points

**Comment by rodprogramdev** [comment]
https://rodprogramdev.github.io/fccManilaCreateHero/

**Comment by rodprogramdev** [comment]
I just have a question sir, I'm still not familiar with the process of git in a collaborative environment. Still learning how to push the files to this repository. Can I ask for instructions on how to do it thank you.

**Comment by jromest** [comment]
Hey @rodprogramdev, I hope you are safe at these times. I know it's been a long time since I update regarding this issue but I would like to know if you're still interested in working on this issue? We can work on this issue so we can finish the project.

**Comment by rodprogramdev** [comment]
Thank you sir @jromest, doing fine still stuck in lockdown right now and continuing my studies in coding. I'm still interested to help out in building the project. What can I do to help out in the project? Stay safe sir to you and your family too.

**Comment by jromest** [comment]
I've reviewed your previous PR #34 regarding this issue, there's a lot of changes in styles. You can open a new PR for this issue and start from the start, I could provide you the SVG for the background. Also, make sure you pull the updates from the repo.

**Comment by rodprogramdev** [comment]
Copy sir, I just want to verify, I'm still not familiar that much with doing it correctly. I will be forking the repo, then try to create another Pull Request, then start installing yarn, then create a new createHero branch from where i can try to update and work on the createHero section. I'm working on doing this right now. Just need to familiarize myself on how to do pull request and push to the original branch.

**Comment by rcode321** [comment]
Hi rod, i create a new PR, to create a Hero section @ fcc website. you can add additional features if you want. but i need a approval from @jromest if the branch/section i made is correct. 🙏 😄

**Comment by rodprogramdev** [comment]
I have already cloned the repo and then I'm triying to create a pull request right now sir. I'm wondering on whether I should do it from the fork repo or from the original repository the pull request? Thank you

**Comment by rodprogramdev** [comment]
![4](https://user-images.githubusercontent.com/44669373/83029934-d1c96800-a065-11ea-894b-fb2e4e04e277.png)
Hi sir heres the update on the work that I'm trying to do right now.

**Comment by rodprogramdev** [comment]
![5](https://user-images.githubusercontent.com/44669373/83032258-31c10e00-a068-11ea-926e-8bf67b103214.png)

**Comment by rodprogramdev** [comment]
Still working on the alignment for now of the images and need to adjust the wave effect based from the desired design.
![8](https://user-images.githubusercontent.com/44669373/83034614-05f35780-a06b-11ea-9a1e-f780960bb1dc.png)

**Comment by rodprogramdev** [comment]
Sir did you see the push for changes that I've done? Thanks

**Comment by rodprogramdev** [comment]
![Hnet com-image](https://user-images.githubusercontent.com/44669373/83075452-74a1d680-a0a6-11ea-8a1d-4d33403ab1c0.gif)

**Comment by jromest** [comment]
> Copy sir, I just want to verify, I'm still not familiar that much with doing it correctly. I will be forking the repo, then try to create another Pull Request, then start installing yarn, then create a new createHero branch from where i can try to update and work on the createHero section. I'm working on doing this right now. Just need to familiarize myself on how to do pull request and push to the original branch.

What process of github or pull request you're having difficulty with?

> @jromest Sir did you see the push for changes that I've done? I'm going to work on the responsiveness. Do we have any desired layout for the mobile and other devices that I can use as a reference? Thanks

With regards to your PR #38, please check the **Files changed**, there are no changes made.

As for now, we are only building for the desktop version, no mobile version or responsive design for now. Also, please refrain from using animations.

@rodprogramdev

**Comment by rodprogramdev** [comment]
@jromest Hi sir thanks, I've tried performing the pull request and created #40 and I removed the animation from the header. Should I also remove the animation from the button. I'm going to work on it right now.

**Comment by genesisgabiola** [comment]
Anyone still working on this?
I would like to contribute to this community project as well.
Can I? Thanks!

**Comment by markdino** [comment]
@genesisgabiola @rodprogramdev @jromest Hi guys! I just made a PR #46 about this issue and hoping to be merge.

**Comment by jromest** [comment]
The hero section is done via #46, closing this now.
