### ISSUE TITLE
Enhancement: Footer Text Headers Improvement

### ISSUE THREAD

**Issue by litemikx** [fccManila/fccmanila.github.io#25]
Footer text header smaller than actual list below. 

![2019-10-26_01-06-32](https://user-images.githubusercontent.com/8636946/67590189-ed495900-f78c-11e9-8815-5f14367cdece.png)

Probably increase size to 20-24px. I can work on the change and make a PR after we've decided for a size. 

Cheers!

**Comment by jromest** [comment]
The headings of the quick links in the footer are intentionally small. Please refer to the [design](https://www.figma.com/proto/ZDkwUTcrWZvv67wCdnt6Xu/freeCodeCamp-Manila?node-id=47%3A1&scaling=scale-down-width) in the [Project Plan](https://github.com/fccManila/fccmanila.github.io/blob/develop/PROJECT_PLAN.md) 😄
