### ISSUE TITLE
Create Join the Community Section

### ISSUE THREAD

**Issue by jromest** [fccManila/fccmanila.github.io#3]
Here's what you will be building:
![Join the Community](https://user-images.githubusercontent.com/25174423/66144951-5df0d000-e63c-11e9-8a2b-328a8858728d.png)

Please refer to the [design](https://www.figma.com/proto/ZDkwUTcrWZvv67wCdnt6Xu/freeCodeCamp-Manila?node-id=47%3A1&scaling=scale-down-width), and make sure you read the [project plan](https://github.com/fccManila/fccmanila.github.io/blob/develop/PROJECT_PLAN.md).

If you have any questions, don't hesitate to ask 😄

**Comment by engrleir** [comment]
I want to contribute. Please assign me to this. Thanks!

**Comment by jromest** [comment]
@engrleir, you can choose between this issue or this #2.

**Comment by engrleir** [comment]
ok, let me work on this one (issue #3).
