### ISSUE TITLE
Create Meetup Gallery Section

### ISSUE THREAD

**Issue by jromest** [fccManila/fccmanila.github.io#4]
Here's what you will be building:
![Meetup Gallery](https://user-images.githubusercontent.com/25174423/66145083-a4462f00-e63c-11e9-9b6d-70b24428d0de.png)

Please refer to the [design](https://www.figma.com/proto/ZDkwUTcrWZvv67wCdnt6Xu/freeCodeCamp-Manila?node-id=47%3A1&scaling=scale-down-width), and make sure you read the [project plan](https://github.com/fccManila/fccmanila.github.io/blob/develop/PROJECT_PLAN.md).

If you have any questions, don't hesitate to ask 😄

**Comment by jrraymundo** [comment]
Will do this 😄
