### ISSUE TITLE
Create Get Involved Section

### ISSUE THREAD

**Issue by jromest** [fccManila/fccmanila.github.io#5]
Here's what you will be building:
![Get Involved](https://user-images.githubusercontent.com/25174423/66145170-d22b7380-e63c-11e9-8b55-2fbd9a513cb8.png)

Please refer to the [design](https://www.figma.com/proto/ZDkwUTcrWZvv67wCdnt6Xu/freeCodeCamp-Manila?node-id=47%3A1&scaling=scale-down-width), and make sure you read the [project plan](https://github.com/fccManila/fccmanila.github.io/blob/develop/PROJECT_PLAN.md).

If you have any questions, don't hesitate to ask 😄

**Comment by ericsoncluciano** [comment]
I can help with this part :)

**Comment by jromest** [comment]
Hey @ericsoncluciano, thank you for expressing your interest in contributing to this project, feel free to work on this issue.
