### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by jromest** [fccManila/fccmanila.github.io#6]
Here's what you will be building:
![Footer](https://user-images.githubusercontent.com/25174423/66145232-fe46f480-e63c-11e9-8b5c-b985adc20d11.png)

Please refer to the [design](https://www.figma.com/proto/ZDkwUTcrWZvv67wCdnt6Xu/freeCodeCamp-Manila?node-id=47%3A1&scaling=scale-down-width), and make sure you read the [project plan](https://github.com/fccManila/fccmanila.github.io/blob/develop/PROJECT_PLAN.md).

If you have any questions, don't hesitate to ask 😄

**Comment by bael-666** [comment]
Hi can I contribute on this?

**Comment by jromest** [comment]
Sure @bael-666, thank you for expressing your interest in contributing to this project, feel free to work on this issue.

**Comment by reyesvicente** [comment]
Can I work on this?

**Comment by jromest** [comment]
Sure @reyesvicente, feel free to work on this issue.

**Comment by reyesvicente** [comment]
> Sure @reyesvicente, feel free to work on this issue.

what css framework are we using? or is it just plain ol' css?

**Comment by jromest** [comment]
> what css framework are we using? or is it just plain ol' css?

We're using plain CSS

**Comment by jromest** [comment]
Footer has been manually merged through #12.
